Repository timacosta/PokeArch, pull requests merged in 2024-03, with the labels that each got.

#95 89 add datasource unit tests
  app/src/main/kotlin/com/architects/pokearch/core/framework/network/PokemonServerDataSource.kt
  app/src/main/kotlin/com/architects/pokearch/core/framework/network/model/NetworkPokemon.kt
  app/src/main/kotlin/com/architects/pokearch/core/framework/network/model/NetworkPokemons.kt
  app/src/test/kotlin/com/architects/pokearch/core/framework/network/PokemonServerDataSourceTest.kt
  app/src/test/kotlin/com/architects/pokearch/core/framework/network/interceptor/ConnectivityInterceptorTest.kt
  app/src/test/kotlin/com/architects/pokearch/core/framework/sensors/AccelerometerSensorTest.kt
  data/src/main/kotlin/com/architects/pokearch/data/datasource/PokemonRemoteDataSource.kt
  data/src/main/kotlin/com/architects/pokearch/data/repository/PokeArchRepository.kt
  data/src/test/kotlin/com/architects/pokearch/data/repository/PokeArchRepositoryTest.kt
  data/src/test/kotlin/com/architects/pokearch/data/repository/VibrationRepositoryTest.kt
Labels: enhancement

#94 71 shake n catch unit tests
  app/src/main/kotlin/com/architects/pokearch/ui/features/shakeNCatch/state/ShakeNCatchUiState.kt
  app/src/main/kotlin/com/architects/pokearch/ui/features/shakeNCatch/viewModel/ShakeNCatchViewModel.kt
  app/src/test/kotlin/com/architects/pokearch/core/framework/database/mapper/DomainMapperTest.kt
  app/src/test/kotlin/com/architects/pokearch/core/framework/database/mapper/RealEntityMapperTest.kt
  app/src/test/kotlin/com/architects/pokearch/core/framework/network/mapper/NetworkMappersTest.kt
  app/src/test/kotlin/com/architects/pokearch/ui/features/shakeNCatch/viewModel/ShakeNCatchViewModelTest.kt
  testing/src/main/kotlin/com/architects/pokearch/testing/samples/PokemonInfoSample.kt
  testing/src/main/kotlin/com/architects/pokearch/testing/samples/PokemonSample.kt
  testing/src/main/kotlin/com/architects/pokearch/testing/verifications/coVerifyNever.kt
  testing/src/main/kotlin/com/architects/pokearch/testing/verifications/coVerifyOnce.kt
Labels: enhancement

#101 100 - Readme
  LICENSE.txt
  README.md
  previews/capture_1.png
  previews/capture_2.png
  previews/github_logo.png
Labels: documentation

#99 70 añadir unit tests detailviewmodel
  app/src/main/kotlin/com/architects/pokearch/core/framework/network/interceptor/ConnectivityInterceptor.kt
  app/src/main/kotlin/com/architects/pokearch/ui/components/dialogs/ArchDialog.kt
  app/src/main/kotlin/com/architects/pokearch/ui/components/placeHolders/ErrorScreen.kt
  app/src/main/kotlin/com/architects/pokearch/ui/components/topAppBar/ArchTopAppBar.kt
  app/src/main/kotlin/com/architects/pokearch/ui/features/details/di/DetailViewModelModule.kt
  app/src/main/kotlin/com/architects/pokearch/ui/features/details/di/annotations/PokemonId.kt
  app/src/main/kotlin/com/architects/pokearch/ui/features/details/ui/DetailScreen.kt
  app/src/main/kotlin/com/architects/pokearch/ui/features/details/viewModel/DetailViewModel.kt
  app/src/main/kotlin/com/architects/pokearch/ui/mapper/ErrorDialogManager.kt
  app/src/test/kotlin/com/architects/pokearch/core/framework/database/mapper/RealEntityMapperTest.kt
  app/src/test/kotlin/com/architects/pokearch/core/framework/network/PokemonServerDataSourceTest.kt
  app/src/test/kotlin/com/architects/pokearch/core/framework/network/interceptor/ConnectivityInterceptorTest.kt
  app/src/test/kotlin/com/architects/pokearch/core/framework/sensors/AccelerometerSensorTest.kt
  app/src/test/kotlin/com/architects/pokearch/ui/features/details/viewModel/DetailViewModelTest.kt
  app/src/test/kotlin/com/architects/pokearch/ui/features/shakeNCatch/viewModel/ShakeNCatchViewModelTest.kt
  app/src/test/kotlin/com/architects/pokearch/usecases/PlayCryTest.kt
  config/detekt/detekt.yml
  data/src/main/kotlin/com/architects/pokearch/data/repository/MediaPlayerRepository.kt
  usecases/src/main/kotlin/com/architects/pokearch/usecases/FetchCry.kt
  usecases/src/main/kotlin/com/architects/pokearch/usecases/FetchPokemonDetails.kt
  usecases/src/main/kotlin/com/architects/pokearch/usecases/GetRandomPokemon.kt
  usecases/src/main/kotlin/com/architects/pokearch/usecases/PlayCry.kt
Labels: enhancement

#103 Update README.md
  README.md
Labels: bug

#102 69 añadir unit tests homeviewmodel
  app/src/main/kotlin/com/architects/pokearch/core/di/AppModule.kt
  app/src/main/kotlin/com/architects/pokearch/ui/components/pagingsource/PokemonPagingSource.kt
  app/src/main/kotlin/com/architects/pokearch/ui/components/pagingsource/PokemonPagingSourceFlowBuilder.kt
  app/src/main/kotlin/com/architects/pokearch/ui/features/home/state/HomeUiState.kt
  app/src/main/kotlin/com/architects/pokearch/ui/features/home/ui/HomeScreen.kt
  app/src/main/kotlin/com/architects/pokearch/ui/features/home/viewModel/HomeViewModel.kt
  app/src/main/kotlin/com/architects/pokearch/ui/navigation/NavItem.kt
  app/src/test/kotlin/com/architects/pokearch/ui/features/home/viewModel/HomeViewModelTest.kt
  gradle/libs.versions.toml
  testing/build.gradle.kts
  testing/src/main/kotlin/com/architects/pokearch/testing/paging/LazyPagingItemsTest.kt
Labels: enhancement

#105 104 - TeamViewModel tests
  app/src/main/kotlin/com/architects/pokearch/ui/features/team/viewmodel/TeamViewModel.kt
  app/src/test/kotlin/com/architects/pokearch/ui/features/shakeNCatch/viewModel/ShakeNCatchViewModelTest.kt
  app/src/test/kotlin/com/architects/pokearch/ui/features/team/viewmodel/TeamViewModelTest.kt
Labels: enhancement

#96 93 - Compose UI Setup
  app/build.gradle.kts
  app/src/androidTest/assets/are_more_available.json
  app/src/androidTest/assets/fetch_pokemon.json
  app/src/androidTest/assets/fetch_pokemons.json
  app/src/androidTest/kotlin/com/architects/pokearch/di/FakeDatabaseModule.kt
  app/src/androidTest/kotlin/com/architects/pokearch/di/FakeNetworkModule.kt
  app/src/androidTest/kotlin/com/architects/pokearch/di/HiltTestRunner.kt
  app/src/androidTest/kotlin/com/architects/pokearch/remote/MockResponseExtensions.kt
  app/src/androidTest/kotlin/com/architects/pokearch/remote/MockWebServerRule.kt
  app/src/androidTest/kotlin/com/architects/pokearch/ui/PokeArchAppTest.kt
  app/src/androidTest/kotlin/com/architects/pokearch/ui/components/ArchTopAppBarTest.kt
  app/src/androidTest/kotlin/com/architects/pokearch/ui/components/ErrorScreenTest.kt
  app/src/androidTest/kotlin/com/architects/pokearch/ui/components/NoSearchResultPlaceHolderTest.kt
  app/src/androidTest/kotlin/com/architects/pokearch/ui/features/home/ui/HomeItemTest.kt
  app/src/debug/AndroidManifest.xml
  app/src/debug/res/xml/network_security_config.xml
  app/src/main/kotlin/com/architects/pokearch/core/framework/network/di/NetworkModule.kt
  app/src/main/kotlin/com/architects/pokearch/core/framework/network/di/annotations/Api.kt
  app/src/main/kotlin/com/architects/pokearch/ui/components/placeHolders/ErrorScreen.kt
  app/src/main/kotlin/com/architects/pokearch/ui/components/placeHolders/NoSearchResultPlaceHolder.kt
  app/src/main/kotlin/com/architects/pokearch/ui/components/topAppBar/ArchSearchTextField.kt
  app/src/main/kotlin/com/architects/pokearch/ui/components/topAppBar/ArchTopAppBar.kt
  app/src/main/kotlin/com/architects/pokearch/ui/features/home/ui/HomeItem.kt
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/network_security_config.xml
  app/src/test/kotlin/com/architects/pokearch/ui/features/shakeNCatch/viewModel/ShakeNCatchViewModelTest.kt
  data/src/test/kotlin/com/architects/pokearch/data/repository/PokeArchRepositoryTest.kt
  gradle/libs.versions.toml
Labels: enhancement
